# Generated by Django 4.1.3 on 2023-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_requestappointment_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='tee@', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tel',
            field=models.CharField(default='078064', max_length=255),
        ),
    ]
