# Generated by Django 4.1.3 on 2023-01-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_email_doctor_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.requestappointment')),
            ],
        ),
    ]
